services:
  dev:
    image: oven/bun:latest
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "bun install && bun x --bun vite --host"
    ports:
      - "5173:5173"
  web:
    image: oven/bun:latest
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "bun install && bun x --bun vite --host --port 5173"
    ports:
      - "${PORT:-8080}:5173"
